SanalGezgin/SanalGezgin/Controllers/yorumYonetimController.cs
using SanalGezgin.kilitle;
using SanalGezgin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SanalGezgin.Controllers
{
    public class yorumYonetimController : kilitleController
    {
        //
        // GET: /yorumYonetim/
        SanalContext context = new SanalContext();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult YorumGetir()
        {
            var yorum = context.Yorums.ToList();
            return View(yorum);
        }
        public ActionResult Sil(int id)
        {
            context.Yorums.Remove(context.Yorums.Find(id));
            
            context.SaveChanges();
            return View("Index", context.Yorums);
        }

    }
}

SanalGezgin/SanalGezgin/Views/yorumYonetim/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/adminMaster.cshtml";
}
@{
    Html.RenderAction("YorumGetir", "yorumYonetim");
}

SanalGezgin/SanalGezgin/Views/yorumYonetim/YorumGetir.cshtml
@{
    Layout = null;
}

@model IEnumerable<SanalGezgin.Models.Yorum>
<div class="box">
    <div class="box-header">
        <h3 class="box-title">Yorumlar</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table id="example2" class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>Adı Soyadı</th>
                    <th>Mesajı</th>
                    <th>Mail Adresi</th>
                    <th>Hangi Makalede</th>
                    <th>Yorum Tarih</th>
                    <th>Yorum Sil</th>
                </tr>
            </thead>
            @foreach (var yorum in Model)
            {
                <tbody>
                    <tr>
                        <td>@yorum.yorumAdiSoyadi</td>
                        <td>@yorum.yorumIcerik</td>
                        <td>@yorum.yorumMail</td>
                        <td>@yorum.Makale.makaleBaslik</td>
                        <td>@yorum.eklenmeTatihi.Value.ToString("dd.MM.yyyy")</td>
                        <td><a href="/yorumYonetim/Sil/@yorum.yorumId">Sil</a></td>
                    </tr>

                </tbody>
            }
        </table>
    </div>
    <!-- /.box-body -->
</div>