SanalGezgin/SanalGezgin/Controllers/SanalPanelController.cs
using SanalGezgin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SanalGezgin.Controllers
{
    public class SanalPanelController : Controller
    {
        //
        // GET: /SanalPanel/

        SanalContext context = new SanalContext();
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public ActionResult editorGiris(FormCollection editor)
        {

            string editorKadi = Request.Form["editorKadi"];
            string editorSifre = Request.Form["editorSifre"];
            
            if (String.IsNullOrEmpty(editorKadi) && String.IsNullOrEmpty(editorSifre))
            {
                return RedirectToAction("/");
            }
            else if (String.IsNullOrEmpty(editorKadi))
            {
                return RedirectToAction("/");
            }
            else if (string.IsNullOrEmpty(editorSifre))
            {
                return RedirectToAction("/");
            }
            else
            {
                var uye = (from i in context.Editors where i.editorSifre == editorSifre && i.editorKadi == editorKadi select i).SingleOrDefault();



                if (uye == null)
                {
                    return RedirectToAction("/");
                }
                else
                {
                    
                    Session["editorKadi"] = uye.editorAdiSoyadi;
                    Session["editorId"] = uye.editorId;
                    Session["editorAktif"] = "1";
                    
                    return RedirectToAction("../SanalYonetim");
                }




            }
        }
        public ActionResult Cikis()
        {
            Session.Clear();
            return RedirectToAction("/");
        }

        public ActionResult iletisimSayi()
        {   
            return View(context.Iletisims.ToList());
        
        }
        public ActionResult makaleSayi()
        {
            return View(context.Makales.ToList());

        }
        public ActionResult yorumSayi()
        {
            return View(context.Yorums.ToList());

        }
        public ActionResult editorSayi()
        {
            return View(context.Editors.ToList());

        }

    }

}

SanalGezgin/SanalGezgin/Views/Shared/MakaleGetir.cshtml
@{
    Layout = null;
}

@model IEnumerable<SanalGezgin.Models.Makale>

@foreach (var makale in Model)
{
    
    <div class="widget searchwidget indexslider">
        <div class="large-widget m30">
            <div class="post row clearfix">
                <div class="col-md-5">
                    <div class="post-media">
                        <a href="/Makale/MakaleDetay/@makale.makaleId">
                            <img alt="" src="~/Content/img/makale/@makale.resim1" class="img-responsive">
                        </a>
                    </div>
                </div>

                <div class="col-md-7">
                    <div class="title-area">
                        <div class="colorfulcats">
                            <a href="#"><span class="label label-primary">Yeni</span></a>
                            <a href="#"><span class="label label-warning">@makale.Kategori.kategoriAdi</span></a>
                        </div>
                        <h3>@makale.makaleBaslik</h3>

                        <div class="large-post-meta">
                            <span class="avatar"><a href="/Makale/MakaleDetay/@makale.makaleId"><img src="/Content/upload/avatar_01.png" alt="" class="img-circle">@makale.Editor.editorAdiSoyadi</a></span>
                            <small>&#124;</small>
                            <span><a href="category.html"><i class="fa fa-clock-o"></i>@makale.makaleTarih.Value.ToString("dd.MM.yyyy")</a></span>
                            
                            
                        </div>
                        <!-- end meta -->
                    </div>
                    <!-- /.pull-right -->
                </div>
            </div>
            <!-- end post -->
        </div>
        <!-- end large-widget -->



    </div>
    

}

SanalGezgin/SanalGezgin/Views/Shared/adminMaster.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Yönetici Paneli</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="/Content/admin/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/Content/admin/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/Content/admin/dist/css/skins/_all-skins.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="/Content/admin/plugins/iCheck/flat/blue.css">
    <!-- Morris chart -->
    <link rel="stylesheet" href="/Content/admin/plugins/morris/morris.css">
    <!-- jvectormap -->
    <link rel="stylesheet" href="/Content/admin/plugins/jvectormap/jquery-jvectormap-1.2.2.css">    
    <!-- Date Picker -->
    <link rel="stylesheet" href="/Content/admin/plugins/datepicker/datepicker3.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="/Content/admin/plugins/daterangepicker/daterangepicker.css">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="/Content/admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

        <header class="main-header">
            <!-- Logo -->
            <a href="index2.html" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini">SG</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg">Sanal Gezgin</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>

                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">


                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="/Content/admin/dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
                                <span class="hidden-xs">@Session["editorKadi"]</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <img src="/Content/admin/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">

                                    <p>
                                        @Session["editorKadi"] - Editor

                                    </p>
                                </li>
                                <!-- Menu Body -->
                                <!-- /.row -->
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Profilim</a>
                            </div>

                            <div class="pull-right">
                                <a href="/SanalPanel/Cikis" class="btn btn-default btn-flat">Çıkış Yap</a>
                            </div>
                        </li>
                    </ul>
                    </li>
                    <!-- Control Sidebar Toggle Button -->
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">

                <!-- search form -->
                <!-- /.search form -->
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu">
                    <li class="header">MENÜ</li>
                    <li><a href="/SanalYonetim"><i class="fa fa-circle-o text-aqua"></i> <span>Anasayfa</span></a></li>
                    <li><a href="/editor"><i class="fa fa-circle-o text-aqua"></i> <span>Editör Yönetimi</span></a></li>
                    
                    <li><a href="/makaleEkle"><i class="fa fa-circle-o text-aqua"></i> <span>Makale Ekle</span></a></li>
                    <li><a href="/makaleYonetim"><i class="fa fa-circle-o text-aqua"></i> <span>Makale Yönetimi</span></a></li>
                    <li><a href="/yorumYonetim"><i class="fa fa-circle-o text-aqua"></i> <span>Yorum Yönetimi</span></a></li>
                    <li><a href="/iletisimPanel"><i class="fa fa-circle-o text-aqua"></i> <span>İletişim Mesajları</span></a></li>

                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    Yönetim Paneli

                </h1>

            </section>

            <!-- Main content -->
            <section class="content">
                <!-- Small boxes (Stat box) -->
                

                <div class="row">
                    

                   @{
                       Html.RenderAction("makaleSayi", "SanalPanel");
                       Html.RenderAction("yorumSayi", "SanalPanel");
                       Html.RenderAction("editorSayi", "SanalPanel");
                       Html.RenderAction("iletisimSayi", "SanalPanel");


                    }


                    <!-- ./col -->
                    
                   
                </div>








                <!-- /.row -->
                <!-- Main row  Alt Kısım Buraya-->






                <div>

                    @RenderBody()



                </div>














                <!-- /.row (main row) -->

            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Versiyon</b> 1.0
            </div>
            <strong>Copyright &copy; 2017 <a href="http://www.sanalgezgin.net">Sanal Gezgin</a></strong> Tüm Hakları Saklıdır.
        </footer>


        <!-- Add the sidebar's background. This div must be placed
             immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 2.2.3 -->
    <script src="/Content/admin/plugins/jQuery/jquery-2.2.3.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
  $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.6 -->
    <script src="/Content/admin/bootstrap/js/bootstrap.min.js"></script>
    <!-- Morris.js charts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="/Content/admin/plugins/morris/morris.min.js"></script>
    <!-- Sparkline -->
    <script src="/Content/admin/plugins/sparkline/jquery.sparkline.min.js"></script>
    <!-- jvectormap -->
    <script src="/Content/admin/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="/Content/admin/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="/Content/admin/plugins/knob/jquery.knob.js"></script>
    <!-- daterangepicker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
    <script src="/Content/admin/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- datepicker -->
    <script src="/Content/admin/plugins/datepicker/bootstrap-datepicker.js"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="/Content/admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
    <!-- Slimscroll -->
    <script src="/Content/admin/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="/Content/admin/plugins/fastclick/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="/Content/admin/dist/js/app.min.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="/Content/admin/dist/js/pages/dashboard.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/Content/admin/dist/js/demo.js"></script>
</body>
</html>