SanalGezgin/SanalGezgin/Models/Editor.cs
using System;
using System.Collections.Generic;

namespace SanalGezgin.Models
{
    public partial class Editor
    {
        public Editor()
        {
            this.Makales = new List<Makale>();
        }

        public int editorId { get; set; }
        public string editorAdiSoyadi { get; set; }
        public string editorKadi { get; set; }
        public string editorSifre { get; set; }
        public Nullable<System.DateTime> editorTarih { get; set; }
        public string editorMail { get; set; }
        public bool editorAktif { get; set; }
        public virtual ICollection<Makale> Makales { get; set; }
    }
}

SanalGezgin/SanalGezgin/Controllers/editorController.cs
using SanalGezgin.kilitle;
using SanalGezgin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SanalGezgin.Controllers
{
    public class editorController : kilitleController
    {
        //
        // GET: /editor/
        SanalContext context = new SanalContext();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult editor(int id)
        {
           
            return View();
        }




        [HttpPost]
        public ActionResult EditorEkle(FormCollection editor)
        {
            Editor model = new Editor();
            model.editorAdiSoyadi = editor["editorAdiSoyadi"].Trim();
            model.editorKadi = editor["editorKadi"].Trim();
            model.editorMail = editor["editorMail"].Trim();
            model.editorSifre = editor["editorSifre"].Trim();
            model.editorTarih = DateTime.Now;
            model.editorAktif = false;
            
            context.Editors.Add(model);
            context.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult EditorGetir()
        {
            var editor = context.Editors.ToList();
            return View(editor);
        }

        public ActionResult Sil(int id)
        {
            context.Editors.Remove(context.Editors.Find(id));

            context.SaveChanges();
            return View("Index", context.Editors);
        }

    }
}

SanalGezgin/SanalGezgin/Views/editor/EditorGetir.cshtml
@{
    Layout = null;
}
@model IEnumerable<SanalGezgin.Models.Editor>
<div class="box">
    <div class="box-header">
        <h3 class="box-title">Editörler</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table id="example2" class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>Editör Kullanıcı Adı</th>
                    <th>Editör Adı Soyadı</th>
                    <th>Editör Mail Adresi</th>
                    <th>Editör Kayıt Tarihi</th>
                    <th>Editör Güncelle</th>
                    <th>Editör Sil</th>
                </tr>
            </thead>
            @foreach (var editor in Model)
            {
            <tbody>
                <tr>
                    <td>@editor.editorKadi</td>
                    <td>@editor.editorAdiSoyadi</td>
                    <td>@editor.editorMail</td>
                    <td>@editor.editorTarih.Value.ToString("dd.MM.yyyy")</td>
                    <td>Güncelle</td>
                    <td><a href="/editor/Sil/@editor.editorId">Sil</a></td>
                </tr>
                
            </tbody>
            }
        </table>
    </div>
    <!-- /.box-body -->
</div>

SanalGezgin/SanalGezgin/Views/editor/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/adminMaster.cshtml";
}

<div class="box box-info">
<div class="box-header with-border">
    <h3 class="box-title">Editör Ekle</h3>
</div>
<!-- /.box-header -->
<!-- form start -->
    <form class="form-horizontal" action="/editor/EditorEkle" method="post">
        <div class="box-body">
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">Adı Soyadı :</label>

                <div class="col-sm-10">
                    <input name="editorAdiSoyadi" type="text" class="form-control" id="inputEmail3" placeholder="Adı Soyadı">
                </div>
            </div>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">Kullanıcı Adı :</label>

                <div class="col-sm-10">
                    <input name="editorKadi" type="text" class="form-control" id="inputEmail3" placeholder="Kullanıcı Adı">
                </div>
            </div>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">E-Posta Adresi :</label>

                <div class="col-sm-10">
                    <input name="editorMail" type="email" class="form-control" id="inputEmail3" placeholder="Email">
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3" class="col-sm-2 control-label">Editör Şifre :</label>

                <div class="col-sm-10">
                    <input name="editorSifre" type="password" class="form-control" id="inputPassword3" placeholder="Password">
                </div>
            </div>

        </div>
        <!-- /.box-body -->
        <div class="box-footer">

            <button type="submit" class="btn btn-info pull-right">Ekle</button>
        </div>
        <!-- /.box-footer -->
    </form>
</div>
@{
    Html.RenderAction("EditorGetir", "editor");


}